RAW_PLAYERNAME_REPLACEMENTS = {
    'Benjamin Mee': ('2324', 'Brentford', ['Ben Mee']),
    'Pierre-Emerick Aubameyang': ('2324', 'Chelsea', ['PE Aubameyang']),
    'Son Heung-min': ('2324', 'Tottenham', ['Son Heungmin']),
    'Pierre Højbjerg': ('2324', 'Tottenham', ['Pierre Emile Hojbjerg']),
    'Mohamed Elneny': ('2324', 'Arsenal', ['Mohamed El Neny']),
    'Stefan Ortega': ('2324', 'Manchester City', ['Stefan Ortega Moreno']),
    "Saman Ghoddoos": ('2324', 'Brentford', ['Saman Ghoddos']),
    "Emerson Palmieri": ('2324', 'West Ham', ['Emerson']),
    "Emerson Royal": ('2324', 'Tottenham', ['Emerson']),
    "Solly March": ('2324', 'Brighton', ['Solomon March']),
    "Hwang Hee-chan": ('2324', 'Wolves', ['Hwang Heechan']),
    "Kiernan Dewsbury-Hall": ('2324', 'Leicester', ['Kiernan Dewsbury Hall']),
    "Jose Luis Gayà": ('2324', 'Valencia', ['Gaya']),
    "Joan Jordan": ('2324', 'Sevilla', ['Jordan']),
    "Àngel Rodriguez": ('2324', 'Mallorca', ['Angel']),
    "Daniel Parejo": ('2324', 'Villarreal', ['Dani Parejo']),
    "Jordi Masip": ('2324', 'Valladolid', ['Masip']),
    "Oscar de Marcos": ('2324', 'Athletic Bilbao', ['De Marcos']),
    "Lucas Pérez": ('2324', 'Cádiz', ['Lucas']),
    "Inigo Ruiz de Galarreta": ('2324', 'Espanyol', ['Ruiz de Galarreta']),
    "Jaime Mata": ('2324', 'Getafe', ['Mata']),
    "Fernando Pacheco": ('2324', 'Espanyol', ['Pacheco']),
    "Dakonam Djene": ('2324', 'Getafe', ['Djene']),
    "Kiko Femenia": ('2324', 'Villarreal', ['Femenia Far']),
    "Anthony Lozano": ('2324', 'Cádiz', ['Choco Lozano']),
    "Neymar": ('2324', 'Paris SG', ['Neymar Jr']),
    "Murilo Cerqueira": ('2324', 'Palmeiras', ['Murilo']),
    "Robson Bambu": ('2324', 'Vasco da Gama', ['Robson']),
    "Cleiton Schwengber": ('2324', 'RB Bragantino', ['Cleiton']),
    "Robson Fernandes": ('2324', 'Coritiba', ['Robson']),
    "Fernando Marcal": ('2324', 'Botafogo', ['Marcal']),
    "Lima": ('2324', 'Fluminense', ['Vinícius Moreira']),
    "José Luis Rodriguez": ('2324', 'Vasco', ['Jose Luis Rodriguez Bebanz']),
    "João Ricardo Riedi": ('2324', 'Fortaleza', ['Joao Ricardo']),
    "Zé Ivaldo": ('2324', 'Athletico Paranaense', ['Jose Ivaldo']),
    "Oscar de Marcos": ('2324', 'Athletic Club', ['De Marcos']),
    "Oscar Mingueza": ('2324', 'Celta Vigo', ['Oscar']),
    "Kamaldeen Sulemana": ('2324', 'Southampton', ['Kamaldeen']),
    "Alex": ('2324', 'Cádiz', ['Alex Fernandez']),
    "Luis Javier Suarez": ('2324', 'Almería', ['Luis Suarez']),
    "Hwang Hee-chan": ('2324', 'Wolves', ['hwang heechan']),
    "Rasmus Kristensen": ('2324', 'Leeds United', ['rasmus kristensen']),
    "Kiernan Dewsbury-Hall": ('2324', 'Leicester City', ['kiernan dewsbury hall']),
    "Hamed Junior Traorè": ('2324', 'Bournemouth', ['hamed traore']),
    "Kamaldeen Sulemana": ('2324', 'Southampton', ['kamaldeen']),
    "Alexis Ruano Delgado": ('2324', 'Cádiz', ['alex']),
    "Jordi Masip": ('2324', 'Real Valladolid', ['masip']),
    "Óscar De Marcos": ('2324', 'Athletic Club', ['de marcos']),
    "Papu Gómez": ('2324', 'Sevilla', ['alejandro gomez']),
    "Ager Aketxe": ('2324', 'Mallorca', ['ruiz de galarreta']),
    "Djene Dakonam": ('2324', 'Getafe', ['dakonam djene']),
    "Iván Sánchez": ('2324', 'Real Valladolid', ['ivan sanchez aguayo']),
    "Gonzalo Melero": ('2324', 'Almería', ['melero']),
    "Ezequiel Ávila": ('2324', 'Osasuna', ['chimy avila']),
    "Carles Aleñá": ('2324', 'Getafe', ['alena']),
    "Óscar García": ('2324', 'Celta Vigo', ['oscar']),
    "Reinildo Mandava": ('2324', 'Atlético Madrid', ['reinildo']),
    "Tino Kadewere": ('2324', 'Mallorca', ['tinotenda kadewere']),
    "José Mari": ('2324', 'Cádiz', ['fali jimenez']),
    "Isaac Carcelén": ('2324', 'Cádiz', ['isaac valencia']),
    "Rafa Mir": ('2324', 'Sevilla', ['rafael mir']),
    "Isi Palazón": ('2324', 'Rayo Vallecano', ['isi palazon']),
    "Javier Galán": ('2324', 'Celta Vigo', ['javier galan']),
    "Alejandro Pozo": ('2324', 'Almería', ['alejandro pozo']),
    "Amath Ndiaye": ('2324', 'Mallorca', ['amath ndiaye']),
    "André Almeida": ('2324', 'Valencia', ['andre almeida']),
    "Santiago Comesaña": ('2324', 'Rayo Vallecano', ['santiago comesana']),
    "Jørgen Strand Larsen": ('2324', 'Celta Vigo', ['jorgen larsen']),
    "Pape Gueye": ('2324', 'Sevilla', ['pape alassane gueye']),
    "Lee Kang-in": ('2324', 'Mallorca', ['lee kangin']),
    "Álvaro Aguado": ('2324', 'Real Valladolid', ['aguado']),
    "Christopher Ramos": ('2324', 'Cádiz', ['christopher ramos']),
    "Luis Suárez": ('2324', 'Almería', ['luis suarez']),
    "Juan Cruz": ('2324', 'Osasuna', ['juan cruz']),
    "Tanguy Nianzou": ('2324', 'Sevilla', ['nianzou kouassi']),
    "Salva Sánchez": ('2324', 'Rayo Vallecano', ['salva sanchez']),
    "Josan Fernández": ('2324', 'Elche', ['josan fernandez']),
    "Fernando Martínez": ('2324', 'Almería', ['fernando martinez']),
    "Gavriel Páez": ('2324', 'Barcelona', ['gavi paez']),
    "Tolgay Arslan": ('2324', 'Udinese', ['tolgay ali arslan']),
    "Jean-Daniel Akpa Akpro": ('2324', 'Empoli', ['jean daniel akpa akpro']),
    "Babis Lykogiannis": ('2324', 'Bologna', ['babis lykogiannis']),
    "Pablo Galdames": ('2324', 'Cremonese', ['pablo galdames']),
    "Dimitrios Nikolaou": ('2324', 'Spezia', ['dimitrios nikolaou']),
    "Lucas Martínez Quarta": ('2324', 'Fiorentina', ['lucas martinez']),
    "Kelvin Amian": ('2324', 'Spezia', ['kelvin amian adou']),
    "Eljif Elmas": ('2324', 'Napoli', ['eljif elmas']),
    "Mohamed Camara": ('2324', 'Roma', ['mohamed mady camara']),
    "Arthur Cabral": ('2324', 'Fiorentina', ['arthur cabral']),
    "Bryan Mbala": ('2324', 'Spezia', ['mbala']),
    "Kim Min-jae": ('2324', 'Napoli', ['kim minjae']),
    "Bremer": ('2324', 'Juventus', ['bremer']),
    "Hamed Junior Traorè": ('2324', 'Sassuolo', ['hamed traore']),
    "Leo Østigård": ('2324', 'Napoli', ['leo ostigard']),
    "Emanuel Aiwu": ('2324', 'Cremonese', ['emanuel aiwu']),
    "M'Baye Niang": ('2324', 'Auxerre', ['mbaye niang']),
    "Benoît Costil": ('2324', 'Lille', ['benoit costil']),
    "Elbasan Rashani": ('2324', 'Clermont Foot', ['elbasan rashani']),
    "Michael Barreto": ('2324', 'Ajaccio', ['michael barreto']),
    "Leonardo Fernández": ('2324', 'Lille', ['leonardo']),
    "Mama Baldé": ('2324', 'Troyes', ['mama balde']),
    "Fabian Ruiz": ('2324', 'Paris SG', ['fabian ruiz']),
    "Boubacar Kouyaté": ('2324', 'Montpellier', ['boubacar kouyate']),
    "Pierre Lees-Melou": ('2324', 'Brest', ['pierre lees melou']),
    "Nuno Joia": ('2324', 'Auxerre', ['nuno joia']),
    "Alexis Claude-Maurice": ('2324', 'Lens', ['alexis claude maurice']),
    "Bévic Moussiti-Oko": ('2324', 'Ajaccio', ['bevic moussiti']),
    "Jean-Daniel N'Guessan Kouamé": ('2324', 'Troyes', ["n'guessan kouame"]),
    "Mathias Pereira Lage": ('2324', 'Brest', ['mathias pereira']),
    "Yan Valery": ('2324', 'Angers', ['yan valery']),
    "Timothy Weah": ('2324', 'Lille', ['tim weah']),
    "Souleyman Doumbia": ('2324', 'Angers', ['souleymane doumbia']),
    "Pape Gueye": ('2324', 'Marseille', ['pape alassane gueye']),
    "Caio Henrique": ('2324', 'Monaco', ['caio henrique']),
    "Younousse Ndayishimiye": ('2324', 'Nice', ['youssuf ndayishimiye']),
    "Montassar Talbi": ('2324', 'Lorient', ['montassar omar talbi']),
    "Andrea Gravillon": ('2324', 'Reims', ['andreaw gravillon']),
    "Khephren Thuram-Ulie": ('2324', 'Nice', ['khephren thuram-ulie']),
    "David Pereira": ('2324', 'Lens', ['david pereira']),
    "Sépé Elye Wahi": ('2324', 'Montpellier', ['sepe elye wahi']),
    "Maxim Choupo-Moting": ('2324', 'Bayern Munich', ['maxim choupo-moting']),
    "Gian-Luca Waldschmidt": ('2324', 'Wolfsburg', ['gian-luca waldschmidt']),
    "Lee Jae-sung": ('2324', 'Mainz 05', ['lee jaesung']),
    "Munas Dabbur": ('2324', 'Hoffenheim', ['munas dabbur']),
    "Ramy Bensebaini": ('2324', "Borussia M'Gladbach", ['rami bensebaini']),
    "Vasileios Lampropoulos": ('2324', 'Bochum', ['vasileios lampropoulos']),
    "Sehrou Guirassy": ('2324', 'Stuttgart', ['sehrou guirassy']),
    "Gil Dias": ('2324', 'Stuttgart', ['gil dias']),
    "Jordan Siebatcheu": ('2324', 'Union Berlin', ['jordan siebatcheu']),
    "Kou Itakura": ('2324', "Borussia M'Gladbach", ['kou itakura']),
    "Ohis Felix Uduokhai": ('2324', 'Augsburg', ['ohis uduokhai']),
    "Stanley Nsoki": ('2324', 'Hoffenheim', ['stanley nsoki']),
    "Buta": ('2324', 'Eintracht Frankfurt', ['buta']),
    "Evan Ndicka": ('2324', 'Eintracht Frankfurt', ["evan n'dicka"]),
    "Iago Borduchi": ('2324', 'Augsburg', ['iago borduchi']),
    "Jeong Woo-yeong": ('2324', 'Freiburg', ['jeong wooyeong']),
    "Rafael Santos Borré": ('2324', 'Eintracht Frankfurt', ['rafael santos borre']),
    "Cauly": ('2324', 'Bahia', ['cauly']),
    "Henrique Adriano": ('2324', 'Coritiba', ['henrique adriano']),
    "Rafael Sóbis": ('2324', 'Cruzeiro', ['rafael']),
    "Aloísio Chulapa": ('2324', 'América-MG', ['aloisio']),
    "Rafael Moura": ('2324', 'São Paulo', ['rafael']),
    "Bruno Alves": ('2324', 'Grêmio', ['bruno alves']),
    "Éverton Ribeiro": ('2324', 'Flamengo', ['everaldo']),
    "Giuliano": ('2324', 'Corinthians', ['giuliano']),
    "Leonardo Gil": ('2324', 'Vasco da Gama', ['leonardo']),
    "Ramiro Moschen Benetti": ('2324', 'Cruzeiro', ['ramiro']),
    "Tinga": ('2324', 'Fortaleza', ['tinga']),
    "Zé Welison": ('2324', 'Fortaleza', ['ze welison']),
    "Juan Lucero": ('2324', 'Fortaleza', ['juan lucero']),
    "Aderlan Santos": ('2324', 'RB Bragantino', ['aderlan']),
    "Marllon": ('2324', 'Cuiabá', ['marllon']),
    "Matheus Jussa": ('2324', 'Cruzeiro', ['matheus jussa']),
    "Leandro Fernandes": ('2324', 'América-MG', ['leandro martinez']),
    "Vinicius Vina": ('2324', 'Grêmio', ['vinicius vina']),
    "Iury": ('2324', 'Cuiabá', ['iury']),
    "Luan": ('2324', 'Palmeiras', ['luan']),
    "Patrick Bezerra": ('2324', 'Atlético-MG', ['patrick bezerra']),
    "Victor Sa": ('2324', 'Botafogo', ['victor sa']),
    "Eder Ferreira": ('2324', 'América-MG', ['eder ferreira']),
    "Allyson": ('2324', 'Cuiabá', ['allyson']),
    "Bruno Rodrigues": ('2324', 'Cruzeiro', ['bruno nascimento']),
    "Guilherme Augusto": ('2324', 'Fortaleza', ['guilherme augusto']),
    "João Ricardo": ('2324', 'Fortaleza', ['joao ricardo']),
    "Andrey Galvão": ('2324', 'Coritiba', ['andrey']),
    "Puma Rodríguez": ('2324', 'Vasco da Gama', ['Jose Luis Rodriguez Bebanz']),
    "Robson Fernandes": ('2324', 'Coritiba', ['robson fernandes']),
    "Gabriel Martinelli": ('2324', 'Arsenal', ['Martinelli']),
    "Gabriel Magalhães": ('2324', 'Arsenal', ['Gabriel Dos Santos', 'Gabriel']),
    "Emiliano Buendía": ('2324', 'Aston Villa', ['Emi Buendia']),
    "Vitaliy Mykolenko": ('2324', 'Everton', ['Vitalii Mykolenko']),
    "Nacho Fernández": ('2324', 'Real Madrid', ['Nacho']),
    "Kike Garcia": ('2324', 'Osasuna', ['Kike']),
    "Memphis Depay": ('2324', 'Atlético Madrid', ['Memphis']),
    "Matías Zaracho": ('2324', 'Atlético-MG', ['Federico Zaracho']),
    "Rasmus Kristensen": ('2324', 'Leeds United', ['Rasmus Nissen'])
}

PLAYERNAME_REPLACEMENTS = {}
for playername, replacement in RAW_PLAYERNAME_REPLACEMENTS.items():
    (season, club, replacements) = replacement
    for replacement in replacements:
        PLAYERNAME_REPLACEMENTS[(replacement.lower(), season, club)] = playername